name: my first workflow
on:
  push:
    branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -name: welcome message
             run: echo"my first project"

            -name: learn githubaction
             run: echo"will learn"
            