name: workflow2

on:
  push:
    branches: 
      - master

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: list of files
        run: ls -lrta 

      - name: list of fies
        run: cat file1.txt
